CREATE DATABASE SUL;

CREATE TABLE IF NOT EXISTS CATEGORY
(
	CATE_NO NUMERIC(10) NOT NULL,
	CATE_NM VARCHAR(20) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
;


CREATE TABLE IF NOT EXISTS REVIEW
(
	REVIEW_NO NUMERIC(10) NOT NULL,
	ALC_NO NUMERIC(10) NOT NULL,
	TITLE VARCHAR(200),
	GRADE NUMERIC(5),
	CONTENT TEXT,
	REG_DT DATETIME,
	MODI_DT DATETIME,
	USER_NM VARCHAR(20),
	REVIEW_PWD VARCHAR(20),
	FILE_NO NUMERIC(10)
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
;

CREATE TABLE IF NOT EXISTS INFORMATION
(
	ALC_NO NUMERIC(20) NOT NULL,
	ALC_NM VARCHAR(50) NOT NULL,
	CATE_NO NUMERIC(10),
	VOL NUMERIC(10),
	PRODUCTOR VARCHAR(20),
	DETAIL TEXT,
	FILE_NO NUMERIC(10),
	EXP_YN VARCHAR(1) DEFAULT 'N'
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
;

CREATE TABLE IF NOT EXISTS ALC_FILE
(
	FILE_NO NUMERIC(10) NOT NULL,
	FILE_PATH VARCHAR(100),
	FILE_NM VARCHAR(100),
	FILE_EXT VARCHAR(10)
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
;

CREATE TABLE IF NOT EXISTS GRADE
(
	ALC_NO NUMERIC(10) NOT NULL,
	AVG_GRADE NUMERIC(10),
	UPDT_DT DATETIME
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
;

ALTER TABLE category ADD PRIMARY KEY(CATE_NO);
ALTER TABLE REVIEW ADD PRIMARY KEY(REVIEW_NO);
CREATE INDEX IDX_REVIEW ON review(REVIEW_NO, ALC_NO, TITLE, grade);
ALTER TABLE information ADD PRIMARY KEY(ALC_NO);
CREATE INDEX IDX_INFORMATION ON INFORMATION(ALC_NO, ALC_NM);
ALTER TABLE ALC_FILE ADD PRIMARY KEY(FILE_NO);
ALTER TABLE GRADE ADD PRIMARY KEY(ALC_NO);