


CREATE DATABASE SUL;

CREATE TABLE IF NOT EXISTS CATEGORY
(
	CATE_NO float(10,0) NOT NULL AUTO_INCREMENT,
	CATE_NM VARCHAR(20) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=INNODB DEFAULT CHARSET=utf8;
;


CREATE TABLE IF NOT EXISTS REVIEW
(
  `REVIEW_NO` float(10,0) NOT NULL AUTO_INCREMENT,
  `ALC_NO` float(10,0) NOT NULL,
  `TITLE` varchar(200) DEFAULT NULL,
  `GRADE` double DEFAULT NULL,
  `CONTENT` text DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `MODI_DT` datetime DEFAULT NULL,
  `USER_NM` varchar(20) DEFAULT NULL,
  `REVIEW_PWD` varchar(100) DEFAULT NULL,
  `FILE_NO` decimal(10,0) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
;

CREATE TABLE IF NOT EXISTS INFORMATION
(
  `ALC_NO` float(20,0) NOT NULL AUTO_INCREMENT,
  `ALC_NM` varchar(50) NOT NULL,
  `CATE_NO` decimal(10,0) DEFAULT NULL,
  `VOL` decimal(10,0) DEFAULT NULL,
  `PRODUCTOR` varchar(20) DEFAULT NULL,
  `DETAIL` text DEFAULT NULL,
  `FILE_NO` decimal(10,0) DEFAULT NULL,
  `EXP_YN` varchar(1) DEFAULT 'N'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
;

CREATE TABLE IF NOT EXISTS ALC_FILE
(
	FILE_NO float(10,0) NOT NULL AUTO_INCREMENT,
	FILE_PATH VARCHAR(100),
	FILE_NM VARCHAR(100),
	FILE_EXT VARCHAR(10)
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
;

CREATE TABLE IF NOT EXISTS GRADE
(
	ALC_NO NUMERIC(10) NOT NULL,
	AVG_GRADE DOUBLE,
	UPDT_DT DATETIME
)
COLLATE='utf8_general_ci'
ENGINE=INNODB
;

ALTER TABLE category ADD PRIMARY KEY(CATE_NO);
ALTER TABLE REVIEW ADD PRIMARY KEY(REVIEW_NO);
CREATE INDEX IDX_REVIEW ON review(REVIEW_NO, ALC_NO, TITLE, grade);
ALTER TABLE information ADD PRIMARY KEY(ALC_NO);
CREATE INDEX IDX_INFORMATION ON INFORMATION(ALC_NO, ALC_NM);
ALTER TABLE ALC_FILE ADD PRIMARY KEY(FILE_NO);
ALTER TABLE GRADE ADD PRIMARY KEY(ALC_NO);

-- 사용자 계정 생성
CREATE USER 'sul'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON sul.* TO 'sul'@'%';

FLUSH PRIVILEGES;